[build]
builder = "railpack"
buildCommand = "pnpm next build --experimental-build-mode compile && pnpm next build --experimental-build-mode generate-env"

[deploy]
releaseCommand = "npx payload migrate"