[build]
builder = "railpack"
buildCommand = "pnpm next build --experimental-build-mode compile && pnpm next build --experimental-build-mode generate-env"

[deploy]
releaseCommand = "npx payload migrate"
startCommand = "sh -c "whoami && ls -la / && ls -la /data 2>/dev/null || echo '/data missing' && exit 1""